#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MCP_DIR="${ROOT}/mcp/expense-tracker"
VENV="${MCP_DIR}/.venv"
DB_DIR="${HOME}/expenses/data"
DB_PATH="${DB_DIR}/expenses.db"
QUIET="${QUIET:-}"
BOOTSTRAP_DB="${BOOTSTRAP_DB:-1}"

log() {
  if [[ -z "${QUIET}" ]]; then
    echo "$@"
  fi
}

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required" >&2
  exit 1
fi

log "==> Hermes Expense Tracker bootstrap"
log "    Repo: ${ROOT}"
log "==> Creating MCP virtualenv"

python3 -m venv "${VENV}"
if [[ -n "${QUIET}" ]]; then
  "${VENV}/bin/pip" install -q --upgrade pip
  "${VENV}/bin/pip" install -q -r "${MCP_DIR}/requirements.txt"
else
  "${VENV}/bin/pip" install --upgrade pip
  "${VENV}/bin/pip" install -r "${MCP_DIR}/requirements.txt"
fi

if [[ "${BOOTSTRAP_DB}" == "1" ]]; then
  LOCALE="${EXPENSE_LOCALE:-}"
  if [[ -z "${LOCALE}" && -f "${HOME}/expenses/locale" ]]; then
    LOCALE="$(tr -d '[:space:]' < "${HOME}/expenses/locale")"
  fi
  case "${LOCALE}" in en|es) ;; *) LOCALE="es" ;; esac

  log "==> Initializing shared database at ${DB_PATH} (schema + categories, locale=${LOCALE})"
  mkdir -p "${DB_DIR}"
  export EXPENSE_DB_PATH="${DB_PATH}"
  export PYTHONPATH="${MCP_DIR}:${PYTHONPATH:-}"
  "${VENV}/bin/python" - <<PY
from expense_tracker.db import init_db
init_db(seed="categories", locale="${LOCALE}")
PY
fi

ENV_SNIPPET="${ROOT}/.env.paths"
cat > "${ENV_SNIPPET}" <<EOF
# Generated by bootstrap.sh — append to each profile .env
EXPENSE_MCP_PYTHON=${VENV}/bin/python
EXPENSE_MCP_SERVER_PATH=${MCP_DIR}/server.py
EXPENSE_DB_PATH=${DB_PATH}
EOF

if [[ -z "${QUIET}" ]]; then
  if [[ "${BOOTSTRAP_DB}" == "1" ]]; then
    echo "==> Database ready: ${DB_PATH}"
  fi
  echo "==> Wrote path variables to ${ENV_SNIPPET}"
  echo
  echo "Next steps:"
  echo "  1. ./install.sh"
  echo "  2. Hermes: hermes setup or profile config.yaml (model)"
  echo "  3. <slug> gateway setup && <slug> gateway start"
fi
